name: Post changelog
on:
  release:
    types: released

jobs:
  post-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Send changelog to telegram channel
        uses: tyagdit/release-telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          channel: ${{ secrets.CHANGELOG_CHANNEL_ID }}
          changelog: ${{ github.event.release.body }}
      - name: 'Post to Nostr'
        run: |
          go install github.com/fiatjaf/noscl@latest
          ~/go/bin/noscl setprivate '${{ secrets.NOSTROS_PRIVATE_KEY }}'
          ~/go/bin/noscl relay add "wss://brb.io"
          ~/go/bin/noscl relay add "wss://nostr-pub.wellorder.net"
          ~/go/bin/noscl relay add "wss://nostr.developer.li"
          ~/go/bin/noscl relay add "wss://nostr.oxtr.dev"
          ~/go/bin/noscl relay add "wss://nostr.swiss-enigma.ch"
          ~/go/bin/noscl relay add "wss://relay.nostr.snblago.com"
          ~/go/bin/noscl relay add "wss://nos.lol"
          ~/go/bin/noscl relay add "wss://relay.austrich.net"
          ~/go/bin/noscl relay add "wss://nostr.cro.social"
          ~/go/bin/noscl relay add "wss://relay.koreus.social"
          ~/go/bin/noscl relay add "wss://spore.ws"
          ~/go/bin/noscl relay add "wss://nostr.web3infra.xyz"
          ~/go/bin/noscl relay add "wss://nostr.snblago.com"
          ~/go/bin/noscl relay add "wss://relay.nostrified.org"
          ~/go/bin/noscl relay add "wss://relay.ryzizub.com"
          ~/go/bin/noscl relay add "wss://relay.wellorder.net"
          ~/go/bin/noscl relay add "wss://nostr.btcmp.com"
          ~/go/bin/noscl relay add "wss://relay.nostromo.social"
          ~/go/bin/noscl relay add "wss://relay.stoner.com"
          ~/go/bin/noscl relay add "wss://nostr.massmux.com"
          ~/go/bin/noscl relay add "wss://nostr.robotesc.ro"
          ~/go/bin/noscl relay add "wss://relay.humanumest.social"
          ~/go/bin/noscl relay add "wss://relay-local.cowdle.gg"
          ~/go/bin/noscl relay add "wss://nostr-2.afarazit.eu"
          ~/go/bin/noscl relay add "wss://nostr.data.haus"
          ~/go/bin/noscl relay add "wss://nostr-pub.wellorder.net"
          ~/go/bin/noscl relay add "wss://nostr.thank.eu"
          ~/go/bin/noscl relay add "wss://relay-dev.cowdle.gg"
          ~/go/bin/noscl relay add "wss://nostrsxz4lbwe-nostr.functions.fnc.fr-par.scw.cloud"
          ~/go/bin/noscl relay add "wss://relay.nostrcheck.me"
          ~/go/bin/noscl relay add "wss://relay.nostrich.de"
          ~/go/bin/noscl relay add "wss://nostr.com.de"
          ~/go/bin/noscl relay add "wss://relay.nostr.scot"
          ~/go/bin/noscl relay add "wss://nostr.8e23.net"
          ~/go/bin/noscl relay add "wss://nostr.mouton.dev"
          ~/go/bin/noscl relay add "wss://nostr.l00p.org"
          ~/go/bin/noscl relay add "wss://nostr.island.network"
          ~/go/bin/noscl relay add "wss://nostr.handyjunky.com"
          ~/go/bin/noscl relay add "wss://relay.valera.co"
          ~/go/bin/noscl relay add "wss://relay.nostr.vet"
          ~/go/bin/noscl relay add "wss://tmp-relay.cesc.trade"
          ~/go/bin/noscl relay add "wss://relay.dwadziesciajeden.pl"
          ~/go/bin/noscl relay add "wss://nostr-1.afarazit.eu"
          ~/go/bin/noscl relay add "wss://lbrygen.xyz"
          ~/go/bin/noscl relay add "wss://soloco.nl"
          ~/go/bin/noscl publish "${{ github.event.release.body }}"
